### ISSUE TITLE
Property 'toBeObservable' does not exist on type 'Matchers<void>'.

### ISSUE THREAD

**Issue by wallace41290** [blove/ngrx-testing#1]
I just cloned the repo, did an npm install, but I get a linting error anytime you use `toBeObservable`:
`Property 'toBeObservable' does not exist on type 'Matchers<void>'.`

do you see this too or do I have something weird on my machine?

**Comment by blove** [comment]
Good catch. I've resolved all linting issues in the latest commit to master. I also added Travis and configured it to run the lint rules.

**Comment by blove** [comment]
@wallace41290 disregard my previous message. This appears to be an issue with jasmine-marbles. I've submitted and issue and PR: https://github.com/synapse-wireless-labs/jasmine-marbles/issues/28
